apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-frontend
  namespace: troubleshooting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-frontend
  template:
    metadata:
      labels:
        app: webapp-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "3Mi"
            cpu: "30m"
          limits:
            memory: "3Mi"
            cpu: "30m"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-service
  namespace: troubleshooting
spec:
  selector:
    app: webapp-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: troubleshooting
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - /bin/sh
      - -c
      - |
        header=$(head -c 32288 /dev/zero | tr '\0' 'a')
        while true; do
          for i in $(seq 1 1550); do
            wget -q -O- --header="X-My-Header: $header" http://webapp-frontend-service &
          done
          wait
        done
