# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "controller", primary: true do |controller|
    controller.vm.network "private_network", ip: "10.42.42.5", virtualbox__intnet: "management"
    controller.vm.network :forwarded_port, guest: 80, host: 8080
    controller.vm.network :forwarded_port, guest: 6080, host: 6080
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

  config.vm.define "network" do |network|
    network.vm.network "private_network", ip: "10.42.42.10", virtualbox__intnet: "management"
    network.vm.network "private_network", ip: "192.168.33.100", virtualbox__intnet: "instances"
    network.vm.network "private_network", ip: "10.12.34.56", virtualbox__intnet: "external"
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
  end

  config.vm.define "compute" do |compute|
    compute.vm.network "private_network", ip: "10.42.42.11", virtualbox__intnet: "management"
    compute.vm.network "private_network", ip: "192.168.33.111", virtualbox__intnet: "instances"
    config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--cpus", "1"]
      vb.customize ["modifyvm", :id, "--memory", "2048"]
    end
  end

end
