apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: vote-app
spec:
  limits:
  - default:
      memory: "256Mi"
      cpu: "200m"
    defaultRequest:
      memory: "128Mi"
      cpu: "100m"
    type: Container
