# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "controller", primary: true do |controller|
    controller.vm.hostname = "controller"
    controller.vm.network "private_network", ip: "10.42.42.5", virtualbox__intnet: "management"
    controller.vm.network "private_network", ip: "192.168.33.100", virtualbox__intnet: "instances"
    controller.vm.network "private_network", virtualbox__intnet: "external"
    controller.vm.network :forwarded_port, guest: 80, host: 8080
    controller.vm.network :forwarded_port, guest: 6080, host: 6080
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "4096"
    end
  end

  config.vm.define "compute" do |compute|
    compute.vm.hostname = "compute"
    compute.vm.network "private_network", ip: "10.42.42.11", virtualbox__intnet: "management"
    compute.vm.network "private_network", ip: "192.168.33.111", virtualbox__intnet: "instances"
    compute.vm.network "private_network", virtualbox__intnet: "external"
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "1024"
    end
  end

end
