apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: vote-app
  labels:
    app: result
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: result
  ports:
  - port: 80
    targetPort: 80
