# --- MANIFESTE BOGUÉ (bad-app.yaml) ---
# Problème : Le Namespace impose un quota de mémoire maximale globale (500Mi), mais le Pod réclame 1Gi.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-quota
  namespace: default
spec:
  hard:
    requests.memory: "500Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-heavy-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-heavy-app
  template:
    metadata:
      labels:
        app: memory-heavy-app
    spec:
      containers:
      - name: app
        image: nginx:1.25-alpine
        resources:
          requests:
            # ERREUR : La requête (1Gi) dépasse le quota total toléré dans le Namespace (500Mi)
            memory: "1Gi"
            cpu: "100m"