{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "voting-app.fullname" . }}-ingress
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.vote }}
    - {{ .Values.ingress.hosts.result }}
    secretName: {{ .Values.ingress.tls.secretName }}
  rules:
  - host: {{ .Values.ingress.hosts.vote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "voting-app.fullname" . }}-vote
            port:
              number: 80
  - host: {{ .Values.ingress.hosts.result }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "voting-app.fullname" . }}-result
            port:
              number: 80
{{- end }}
