apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voting-app.fullname" . }}-secret
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
