# --- MANIFESTE CORRIGÉ (fixed-app.yaml) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hardened-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hardened-web
  template:
    metadata:
      labels:
        app: hardened-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 80
        volumeMounts:
        # CORRECTION : Montage de volumes enregistrés en mémoire vive (emptyDir) sur les points d'écriture nécessaires
        - name: run-vol
          mountPath: /var/run
        - name: cache-vol
          mountPath: /var/cache/nginx
      volumes:
      - name: run-vol
        emptyDir: {}
      - name: cache-vol
        emptyDir: {}