apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: vote-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: vote-app
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-read-configmaps
  namespace: vote-app
subjects:
- kind: ServiceAccount
  name: worker-sa
  namespace: vote-app
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io
